### ISSUE TITLE
Cubic-spline Interpolation in SE3

### ISSUE THREAD

**Issue by MichaelFYang** [pypose/pypose#110]
### 🚀 The feature, motivation and pitch

A cubic spline is a [spline](https://mathworld.wolfram.com/Spline.html) constructed of piecewise third-order [polynomials](https://mathworld.wolfram.com/Polynomial.html) which pass through a set of m control points. It is quite useful for trajectory generation and smoothness. The current implementation support only interpolation with the (x, y, z) coordinate but does not support SE3 for orientation interpolation. Here attached an example code that supports branch operation for cubic-spline interpolation in (x, y, z):

```
import torch

class CubicSplineTorch:
    # Reference: https://stackoverflow.com/questions/61616810/how-to-do-cubic-spline-interpolation-and-integration-in-pytorch
    def __init__(self):
        return None

    def h_poly(self, t):
        alpha = torch.arange(4, device=t.device, dtype=t.dtype)
        tt = t[:, None, :]**alpha[None, :, None]
        A = torch.tensor([
            [1, 0, -3, 2],
            [0, 1, -2, 1],
            [0, 0, 3, -2],
            [0, 0, -1, 1]
            ], dtype=t.dtype, device=t.device)
        return A @ tt

    def interp(self, x, y, xs):
        m = (y[:, 1:, :] - y[:, :-1, :]) / torch.unsqueeze(x[:, 1:] - x[:, :-1], 2)
        m = torch.cat([m[:, None, 0], (m[:, 1:] + m[:, :-1]) / 2, m[:, None, -1]], 1)
        idxs = torch.searchsorted(x[0, 1:], xs[0, :])
        dx = x[:, idxs + 1] - x[:, idxs]
        hh = self.h_poly((xs - x[:, idxs]) / dx)
        hh = torch.transpose(hh, 1, 2)
        out = hh[:, :, 0:1] * y[:, idxs, :]
        out = out + hh[:, :, 1:2] * m[:, idxs] * dx[:,:,None]
        out = out + hh[:, :, 2:3] * y[:, idxs + 1, :]
        out = out + hh[:, :, 3:4] * m[:, idxs + 1] * dx[:,:,None]
        return out


def TrajGeneratorFromPoints(points, steps=0.1): 
    # Points is in se3
    cs_interp = CubicSplineTorch()
    batch_size, num_p, dims = points.shape
    num_p = num_p
    xs = torch.arange(0, num_p-1+steps, steps, device=points.device)
    xs = xs.repeat(batch_size, 1)
    x  = torch.arange(num_p, device=points.device, dtype=points.dtype)
    x  = x.repeat(batch_size, 1)
    waypoints = cs_interp.interp(x, points, xs)
    return waypoints 
```

Then it is good to have an extension using PyPose to support full SE3 (translation + orientation) cubic-spline interpolation.

- Input:  Points in SE3 shape: (batch_size, n_poins, 7); step size
- Output: Interpolated Points in SE3 - Shape (batch_size, n_points / step_size + 1, 7)

**Comment by urbste** [comment]
Hi guys, 
I just found pypose. Great work :)

I was wondering, as you are already discussing spline interpolation here, if it might be possible with the pypose framework to directly go a step further.

Continuous time trajectory estimation is a powerful tool to fuse different kind of (a)synchronous measurements (Rolling Shutter, GPS, IMU, Event Cameras, Lidar) to a trajectory estimation problem as shown in these papers:
[SplineFusion](http://www.bmva.org/bmvc/2013/Papers/paper0093/paper0093.pdf) was one of the first modeling C2 continuous splines in SE3.
Later it was shown, that modeling the spline in "split" trajectories, i.e. SO3 and R3 separately works better and optimization is [faster](https://arxiv.org/pdf/1805.02543.pdf).
Analytical jacobians were derived in this [paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sommer_Efficient_Derivative_Computation_for_Cumulative_B-Splines_on_Lie_Groups_CVPR_2020_paper.pdf)
In addition, it can be used for camera / IMU calibration (e.g. Kalibr).

I just wanted to start a discussion if you think the tools are already there to implement that?
In [Kontiki](https://github.com/hovren/kontiki), the author uses the AutoDiff framework of the ceres-solver and designs various error functions. A different implementation with analytical jacobians can be found here [lie-spline-exp](https://gitlab.com/tum-vision/lie-spline-experiments). 
Maybe if I can find the time I could give it a shot with some guidance from your side?

**Comment by HongLouyemeng** [comment]
I like this topic！
