### ISSUE TITLE
weight matrix in optimization

### ISSUE THREAD

**Issue by wang-chen** [pypose/pypose#126]
### 🐛 Describe the bug

The current implementation for the weight least square problem is to get the Cholesky decomposition of the weight matrix, while it may not be positive-definite.
A better implementation is to get the residual as `R= J.T @ W @ e` and `A = J.T @ W @ J`, which will not need any decomposition.

### Versions

No version needed

**Comment by Jaraxxus-Me** [comment]
Does J mean Jacobian Matrix?

**Comment by Jaraxxus-Me** [comment]
And what is the use of H = J.T @ W @ J ?
Where is H used ?

**Comment by wang-chen** [comment]
Yes, `J` is Jacobian,
-  `J.T @ J` -- > `J.T @ W @ J` refers to this line 
https://github.com/pypose/pypose/blob/44ab958e96bd077639f71d5a86df8c7d1e8ecc9e/pypose/optim/optimizer.py#L455: 

- `J.T @ R` -->  `J.T @ W @ R` refers to this line
https://github.com/pypose/pypose/blob/44ab958e96bd077639f71d5a86df8c7d1e8ecc9e/pypose/optim/optimizer.py#L460

**Comment by Jaraxxus-Me** [comment]
Raising this problem for line455[](url)
![截屏2022-09-08 下午3 54 52 (2)](https://user-images.githubusercontent.com/56875617/189215785-f545b50b-3a1a-4890-a6b6-cdb90b4b38df.png)
