### ISSUE TITLE
Merge TartanAir DataLoader

### ISSUE THREAD

**Issue by wang-chen** [pypose/pypose#145]
### 🚀 The feature, motivation and pitch

The Pull request #129 provides a fast data cacher for (TartanAir)[https://theairlab.org/tartanair-dataset/] datasets, while it doesn't follow the format and data structure of PyPose. Better to refactor it and make it extendable to other datasets as well.

**Comment by zitongzhan** [comment]
The functionality was already implemented by torch dataloader two years ago, so we can just use the original implementation directly.
