### ISSUE TITLE
add PnP

### ISSUE THREAD

**Issue by wang-chen** [pypose/pypose#149]
### 🚀 The feature, motivation and pitch

Refer to [OpenCV PnP](https://docs.opencv.org/4.x/d5/d1f/calib3d_solvePnP.html), a PnP module is often needed in SLAM problems. This PnP solver may also leverage the [RANSAC](#147) module.

**Comment by jingnanshi** [comment]
Design slides: https://docs.google.com/presentation/d/1c2_mSIdkwsmpVjRHa8qjlNaMmJivRnXH3rX9bejMpVE/edit?usp=sharing

**Comment by LueYinny** [comment]
Is this problem solved?

**Comment by wang-chen** [comment]
@LueYinny it is in development and will release after an intensive test.

**Comment by wang-chen** [comment]
closed as #184 merged
