### ISSUE TITLE
Cannot access kitti imu sample data 

### ISSUE THREAD

**Issue by hanskumarKEF** [pypose/pypose#165]
### 🐛 Describe the bug

sample data for Kitti IMU example has broken link https://github.com/pypose/IMU_preintegration/releases/download/Kitti/2011_09_26.zip

### Versions

using latest version from pip install

**Comment by wang-chen** [comment]
just tested, this link still works for me.

**Comment by hanskumarKEF** [comment]
is the IMU_preintegration repo private?

**Comment by wang-chen** [comment]
you can try again now, will fix the link in the next release.

**Comment by wang-chen** [comment]
the link was changed to https://github.com/pypose/pypose/releases/download/v0.2.2/2011_09_26.zip in the newest release v0.2.2
