### ISSUE TITLE
Distance between rotations

### ISSUE THREAD

**Issue by HongLouyemeng** [pypose/pypose#187]
### 🚀 The feature, motivation and pitch

For two rotations, the distance is a very important property

### Alternatives

Here are some reference links
1.http://www.boris-belousov.net/2016/12/01/quat-dist/
2.https://www.cs.cmu.edu/~cga/dynopt/readings/Rmetric.pdf
3.https://lcvmwww.epfl.ch/publications/data/articles/63/Means_and_Averaging_in_the_Group_of_Rotations.pdf

**Comment by wang-chen** [comment]
@ShaoshuSu

**Comment by ShaoshuSu** [comment]
Hi @HongLouyemeng, thanks for your suggestion : ) 
We have noticed that topic and will work on that soon

**Comment by Murphy41** [comment]
The feature has been partly implemented in Pull Request #216 (in posediff function).
