### ISSUE TITLE
Bicycle model example error with EKF model

### ISSUE THREAD

**Issue by HongLouyemeng** [pypose/pypose#189]
### 🐛 Describe the bug

**AttributeError: 'Bicycle' object has no attribute 'A'**
https://github.com/pypose/pypose/blob/fe00ca6a6b213fbbcfc7b68303e967edf5c516a6/examples/module/filter/bicycle.py#L9
https://github.com/pypose/pypose/blob/fe00ca6a6b213fbbcfc7b68303e967edf5c516a6/test/module/test_ekf.py#L10

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.9.10 (main, Jan 15 2022, 11:48:04)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-13.2.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.2.1
[pip3] gpytorch==1.9.0
[pip3] numpy==1.22.4
[pip3] pytorch3d==0.7.0
[pip3] torch==1.13.1
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect

**Comment by wang-chen** [comment]
This should be fixed by this [commit](https://github.com/pypose/pypose/commit/34ebf80b011473e7297949fe6774b0da909571e9).
