### ISSUE TITLE
Add a dataloader for Bundle Adjustment

### ISSUE THREAD

**Issue by zitongzhan** [pypose/pypose#235]
Need to write a dataloader for the [BAL dataset](https://grail.cs.washington.edu/projects/bal/) in order to test the functionality of SBT. 
It is recommended to use TorchData like https://github.com/pypose/pypose/pull/226 to keep implementation short.

**Comment by hxu296** [comment]
I would like to take on this problem.

**Comment by wang-chen** [comment]
> I would like to take on this problem.

That will be great! @zitongzhan can provide more information.
