### ISSUE TITLE
Remove runtime dependency on pytest (or at least loosen version constraint)

### ISSUE THREAD

**Issue by robin-wayve** [pypose/pypose#274]
### 🐛 Describe the bug

`pypose` depends on an exact version of `pytest` at runtime, but as far as I can see, none of the code actually imports anything from it.

If I am missing something, and it is really required, could the version constraint at least be loosened to `>=7.1.2,<8` or similar?

### Versions

0.6.0

**Comment by wang-chen** [comment]
@robin-wayve You may now upgrade by `pip install -U pypose` now.
